project_id = "hyilgirnewnwtthbvbqn"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.market-quotes]
verify_jwt = false

[functions.market-ticker] 
verify_jwt = false

[functions.chat-with-elin]
verify_jwt = false

[functions.create-payment]
verify_jwt = false